// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgjopzYf2UTw3DJlYv8kczSUlYMKTZsg4',
    appId: '1:550401417451:web:aed9b7a3a6c4843d8d1eae',
    messagingSenderId: '550401417451',
    projectId: 'messenger-1729f',
    authDomain: 'messenger-1729f.firebaseapp.com',
    storageBucket: 'messenger-1729f.appspot.com',
    measurementId: 'G-ZQMNF5DF81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLgRxXpwlWsuqn9Lw9LNbQltjmnkjdUBo',
    appId: '1:550401417451:android:6625789206528df98d1eae',
    messagingSenderId: '550401417451',
    projectId: 'messenger-1729f',
    storageBucket: 'messenger-1729f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp3nVCW8_PEt3YgYEJuqh9cHiqEJtLfV8',
    appId: '1:550401417451:ios:f46e9a6d6f6189418d1eae',
    messagingSenderId: '550401417451',
    projectId: 'messenger-1729f',
    storageBucket: 'messenger-1729f.appspot.com',
    iosClientId: '550401417451-9e97en897jolgsu1pcglknhssg1doses.apps.googleusercontent.com',
    iosBundleId: 'com.deargo.flutgram.flutgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp3nVCW8_PEt3YgYEJuqh9cHiqEJtLfV8',
    appId: '1:550401417451:ios:f46e9a6d6f6189418d1eae',
    messagingSenderId: '550401417451',
    projectId: 'messenger-1729f',
    storageBucket: 'messenger-1729f.appspot.com',
    iosClientId: '550401417451-9e97en897jolgsu1pcglknhssg1doses.apps.googleusercontent.com',
    iosBundleId: 'com.deargo.flutgram.flutgram',
  );
}
